apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app4
  namespace: argo-dev
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  source:
    repoURL: hhttps://github.com/onasser1/argocd-paths.git
    targetRevision: HEAD
    path: example/other
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
